### ISSUE TITLE
openssl issue

### ISSUE THREAD

**Issue by dominikl** [ome/omero-server#146]
I'm not sure if it is a server or client side problem, but there seems to be an issue when connecting from a client (maybe just Windows?) using current openssl 1.1.1 to a server using the same current openssl version, see [Installing omero-py on Windows : Ice::SecurityException ](https://forum.image.sc/t/installing-omero-py-on-windows-ice-securityexception/70963) Downgrading to openssl 1.0.2 on the server side seemed to have fixed the problem.
Needs more testing/debugging, e.g. try the same with a Linux client to rule out OS specific issue.

**Comment by dominikl** [comment]
I just tested it again with the same Windows VM connecting to an Ubuntu VM with openssl 1.1.1 and it works. Whatever causes the issue, it seems to be not openssl alone.

**Comment by jburel** [comment]
The PR https://github.com/ome/omero-py/pull/332 might be more suited against this repo or probably better against openmicroscopy
What do you think @dominikl?

**Comment by dominikl** [comment]
I'll close the issue again. I tried again connecting to a fresh Debian VM installation (with openssl 1.1.1) and it works. Can't replicate the issue.
