### ISSUE TITLE
group owner import regression

### ISSUE THREAD

**Issue by mtbc** [ome/omero-server#63]
By the magic of Docker @manics pinned down OMERO 5.4.6 as breaking the ability of group owners to import on members' behalf. This should be fixed.

@pwalczysko points to `LightAdminRolesTest` as useful source material for an integration test. In particular, see `testImporterAsSudoCreateImport` and `testDeleteGroupOwner`.

**Comment by pwalczysko** [comment]
https://forum.image.sc/t/group-owner-import-for-other-failed-omero-importer-5-4-10/28369 is the relevant reporting post

**Comment by dominikl** [comment]
Tested with the latest release 5.5.9 against merge-ci. Setup: Read-only group `import_test` with users `import_test_owner` as owner (light admin with sudo permission) and `import_test_user` as normal user.

No problem with OMERO.Importer. Note: Initially I forgot to make the `import_test_owner` a light admin with sudo permission, which then gave an error on import - like expected I'd assume. Maybe that was the problem?

I also tried with **command line import**, which **does not work like expected**:
```
~/test omero --sudo import_test_user import /home/dominik/Downloads/sponsors.png
Using session for import_test_owner@merge-ci-devspace.openmicroscopy.org:4064. Idle timeout: 10 min. Current group: import_test
2020-02-03 16:13:26,177 312        [      main] INFO          ome.formats.importer.ImportConfig - OMERO Version: 5.5.5
...
2020-02-03 16:13:31,988 6123       [l.Client-1] INFO   ormats.importer.cli.LoggingImportMonitor - IMPORT_DONE Imported file: /home/dominik/Downloads/sponsors.png
Image:99818
Other imported objects:
Fileset:73910

==> Summary
1 file uploaded, 1 fileset created, 1 image imported, 0 errors in 0:00:01.878
```
No error or warning, but the image actually goes into 'Orphaned Images' of the user which does the import.
![Screen Shot 2020-02-03 at 16 20 10](https://user-images.githubusercontent.com/6575139/73670484-328cf900-46a1-11ea-8139-f98e0ae23d9f.png)

**Comment by pwalczysko** [comment]
@dominikl 

> import_test_owner as owner (light admin with sudo permission) and import_test_user as normal user.

No, sorry, this is not what the bug is about. The "owner" must be a plain group owner. Not a light admin of any kind. Just a group owner. The light admin should work, as expected and confirmed by yourself.

**Comment by pwalczysko** [comment]
@dominikl 

> I also tried with command line import, which does not work like expected:

I would read your output as follows - you specified in your cli command who is sudoing. But I do not see any ``-u`` flag, thus you did not specified who to sudo as -> thus there is only one user to deal with. The cli did the reasonable thing then - imported for the only actor who is on the scene... When you do not specify a target dataset with ``-T`` option, then the image is imported into orphaned when cli is used, this is expected.

**Comment by pwalczysko** [comment]
@dominikl aha, sorry, now read your edit of your comment - so I think we are on the same page with regard to cli https://github.com/ome/omero-server/issues/63#issuecomment-581553424

So all works as expected for the light admin - but again, this is not what this bug is about (=group owner, not an admin of any sort)

**Comment by dominikl** [comment]
So a group owner is expected to be able to import as another user - which is a sudo operation - without having sudo permisssion?

**Comment by pwalczysko** [comment]
@dominikl group owner 
1. is expected to import as another user
2. is expected to have sudo perms for the members of his/her group

**Comment by pwalczysko** [comment]
So, once more to re-emphasize - there is an issue here with Group Owner not being able to import for others.

**Comment by pwalczysko** [comment]
@dominikl to clarify the matter somewhat - think about Group Owner as a full admin as long as they move /operate/impot into/manage their own group. The right to import for others (sudo) is fully within that.

**Comment by chris-allan** [comment]
> @dominikl to clarify the matter somewhat - think about Group Owner as a full admin as long as they move /operate/impot into/manage their own group. The right to import for others (sudo) is fully within that.

I don't believe we should be encouraging the workflow of "import for others" as a group owner task. That seems to me a highly niche workflow. Furthermore, the number of potential security boundary conditions this creates and requires us to test for is immense.

**Comment by sukunis** [comment]
I don't think this is a highly niche workflow. For example we have a lot of microscope manager who make the acquisition for other scientists. But it is not intended to give them as many rights as they get with sudo-privileg. And since these are mainly Windows systems, it is not possible to use cli.

**Comment by chris-allan** [comment]
I don't see what the operating system or use of CLI has to do with this.

Under those workflow conditions what is wrong with the data being owned by the person who performed the acquisition or even by a separate "import" user within that group?

**Comment by joshmoore** [comment]
> I don't see what the operating system or use of CLI has to do with this.

To clarify: this bug is about the fact that the import-as functionality doesn't work in insight. In @sukunis' case, the CLI appears to still be functioning and so there were plans to work around the insight bug by remotely making use of the CLI on the server, since installing the Python dependencies etc. on Windows wouldn't be feasible.

**Comment by chris-allan** [comment]
Now I'm even more confused. @dominikl is testing with "light admin with sudo permission", no? Have we established that a scenario where the user is just a group owner functions correctly here?

**Comment by sukunis** [comment]
Import of group owner (**no light admin with sudo permissions**) for another user of a private group failed for OMERO.importer 5.5.8 and 5.5.9 failed with:
omero.SecurityViolation
    serverStackTrace = "ome.conditions.SecurityViolation: Cannot read ome.model.meta.Session:Id_258
                        	at ome.security.basic.BasicACLVoter.throwLoadViolation(BasicACLVoter.java:300)
                        	at ome.security.CompositeACLVoter.throwLoadViolation(CompositeACLVoter.java:92)
                        	at ome.security.ACLEventListener.onPostLoad(ACLEventListener.java:102)
                        	at org.hibernate.engine.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:250)
                        	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:982)
                        	at org.hibernate.loader.Loader.doQuery(Loader.java:857)
                        	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
                        	at org.hibernate.loader.Loader.loadEntity(Loader.java:2037)
                        	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:86)
.....

**Comment by pwalczysko** [comment]
@sukunis Yes, confirming that. This is from OMERO.insight. I have the same error, thank you. And yes, the same workflow tried on CLI ends with a similar error.

@sukunis sorry for the confusion here, I think the bug is there just as reported by yourself originally. We will keep in touch with further info.

**Comment by pwalczysko** [comment]
@jburel CLI error described in https://openmicroscopy.slack.com/archives/C0K5EED3R/p1580991630496600

Insight error described in https://openmicroscopy.slack.com/archives/C0K5EED3R/p1580990842495100

**Comment by jburel** [comment]
I have an integration test for that now

**Comment by mtbc** [comment]
So it is possible that it is the read-only work that broke this?

Running the debugger on a current OMERO, `PublicRepositoryI.persistLogFile`'s call to `session.refresh` fails because `BasicACLVoter` prevents the group sudo session from loading one of `root`'s sessions.

**Comment by mtbc** [comment]
Note feedback from workshop visit -

> Want core facility managers to be able to import for others BUT doesn’t want to make them into Admins (or light admins) since they shouldn’t have access to data from *other* core facilities.

**Comment by pwalczysko** [comment]
Fixed and released, see https://forum.image.sc/t/release-of-omero-server-5-6-2-omero-web-5-7-0-and-omero-iviewer-0-10-0/40463
