### ISSUE TITLE
WARN log noise about fake images

### ISSUE THREAD

**Issue by mtbc** [ome/omero-server#74]
My `Blitz-0.log` notes `WARN` lines like,
```
Enumeration 'Fake' does not exist in 'class omero.model.Format' returning 'null'
```
The `DBEnumCheck` added for [Trac 1662](https://trac.openmicroscopy.org/ome/ticket/1662) specifically avoids adding `Fake` to the database's `format` table.

I wonder if we should either add `Fake` to the table or add a small hack to avoid that warning for fake images.

**Comment by joshmoore** [comment]
I think I would tend toward no hacks rather than 2.
