### ISSUE TITLE
A problem occurred evaluating root project 'omero-server'. when run gradle build 

### ISSUE THREAD

**Issue by busing** [ome/omero-server#94]
I clone the code from Github ,and run cmd "gradle build"  in the root of the project 
but it did not success 
and report an error :
slice2java (\bin\slice2java.exe) not found. Please ensure that Ice is installed and the iceHome property () is correct.

it seem's that problem is  related to the following script
build.gradle : 88 
![image](https://user-images.githubusercontent.com/9995678/80564914-c0b71800-8a21-11ea-8f0b-6a71539d9abd.png)

How can i fix this problem ,thank you

**Comment by joshmoore** [comment]
Hi @busing. You'll need to install the zeros-ice development tools (https://zeroc.com/downloads/ice/3.6) for your platform. The slice2java executable is used to generate code during the cradle build.

**Comment by busing** [comment]
Thank you very much. I have solved this problem .

**Comment by joshmoore** [comment]
Glad to hear it. Let us know how things go.

**Comment by busing** [comment]
At present, gradle is downloading the dependency package, which may take some time. I will consult you later if there are any questions. Thank you for your support . 
This project is very helpful to us , Thank for your work.

**Comment by mtbc** [comment]
In general https://docs.openmicroscopy.org/omero/5.6/developers/installation.html may be a good help, it has a pointer to the prerequisites page though does yet need some further updates. Good luck! We're sure glad that the project is helpful to the community.
