### ISSUE TITLE
can not find symbol when i run gradle build

### ISSUE THREAD

**Issue by busing** [ome/omero-server#95]
![image](https://user-images.githubusercontent.com/9995678/80583216-84e07a80-8a42-11ea-898c-084cf9b85895.png)

![image](https://user-images.githubusercontent.com/9995678/80583312-9f1a5880-8a42-11ea-819c-adb7049020ef.png)

when i run “gradle build”  

report error : can not find symbol
I think there are many other dependency, how can i get them

**Comment by joshmoore** [comment]
Hi @busing. Those files are stored in a subdirectory based on the Ice version:

```
$ git ls-files | grep ShareStore
src/main/ice36/ome/services/sharing/BlobShareStore.java
src/main/ice36/ome/services/sharing/ShareStore.java
```

I fear you've run into a bug in one of our gradle plugins on Windows.

**Comment by busing** [comment]
Thank you for your suggestion, I have solved this problem ,because i installed ice3.7, but there is no code of ice 3.7 in the source code ,only 3.6, so i reinstalled ice 3.6 to solve this problem

**Comment by joshmoore** [comment]
Ah! That makes sense. Sorry for not thinking of that sooner. Thanks for letting us know, @busing.
